title: Berat Arpacı
email: info@beratarpaci.com
description: >-
  İç denetim, katılım finans, faizsiz finans ve sektörel teftiş üzerine düşünceler.
baseurl: "" 
url: "https://beratarpc.github.io"
theme: minima

author:
  name: Berat Arpacı
  email: info@beratarpaci.com

markdown: kramdown
plugins:
  - jekyll-feed
